const defaultMenu=[{id:1,name:"Butter Chicken",price:260,img:"https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80"},{id:2,name:"Paneer Tikka",price:220,img:"https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80"},{id:3,name:"Veg Biryani",price:180,img:"https://images.unsplash.com/photo-1563379091339-03246963d96c?auto=format&fit=crop&w=800&q=80"},{id:4,name:"Masala Dosa",price:140,img:"https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=800&q=80"}];
const foodGallery=[
["Butter Chicken","https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80"],
["Paneer Tikka","https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80"],
["Veg Biryani","https://images.unsplash.com/photo-1563379091339-03246963d96c?auto=format&fit=crop&w=800&q=80"],
["Masala Dosa","https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=800&q=80"],
["Pizza","https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80"],
["Burger","https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80"],
["French Fries","https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80"],
["Noodles","https://images.unsplash.com/photo-1557872943-16a5ac26437e?auto=format&fit=crop&w=800&q=80"],
["Momos","https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&w=800&q=80"],
["Gulab Jamun","https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80"]
];
let menu=JSON.parse(localStorage.getItem("menu")||"null")||defaultMenu,cart=JSON.parse(localStorage.getItem("cart")||"[]"),orders=JSON.parse(localStorage.getItem("orders")||"[]"),settings=JSON.parse(localStorage.getItem("settings")||'{"name":"My Restaurant"}');
const $=id=>document.getElementById(id);function save(){localStorage.setItem("menu",JSON.stringify(menu));localStorage.setItem("cart",JSON.stringify(cart));localStorage.setItem("orders",JSON.stringify(orders));localStorage.setItem("settings",JSON.stringify(settings))}
function render(){$("brand").textContent="🍽️ "+settings.name;$("footerName").textContent=settings.name;$("year").textContent=new Date().getFullYear();$("menu").innerHTML=menu.map(x=>'<article class="card"><img src="'+x.img+'"><div class="p"><h3>'+x.name+'</h3><div class="price">₹'+x.price+'</div><button class="primary" onclick="addToCart('+x.id+')">Add to Cart</button></div></article>').join("");$("cartCount").textContent=cart.reduce((s,x)=>s+x.qty,0)}
function addToCart(id){let x=cart.find(a=>a.id===id);x?x.qty++:cart.push({id,qty:1});save();render();openCart()}function openCart(){renderCart();$("cartModal").style.display="flex"}function renderCart(){if(!cart.length){$("cartItems").innerHTML="<p>Your cart is empty.</p>";$("cartTotal").textContent="0";return}let total=0;$("cartItems").innerHTML=cart.map(c=>{let x=menu.find(m=>m.id===c.id),sub=x.price*c.qty;total+=sub;return '<div class="cart-row"><img src="'+x.img+'"><div><b>'+x.name+'</b><br>₹'+x.price+'</div><div class="qty"><button onclick="changeQty('+x.id+',-1)">−</button>'+c.qty+'<button onclick="changeQty('+x.id+',1)">+</button></div></div>'}).join("");$("cartTotal").textContent=total}
function changeQty(id,d){let x=cart.find(a=>a.id===id);x.qty+=d;if(x.qty<=0)cart=cart.filter(a=>a.id!==id);save();render();renderCart()}function checkout(){if(!cart.length)return alert("Cart is empty");$("cartModal").style.display="none";$("checkoutModal").style.display="flex"}
function placeOrder(e){e.preventDefault();let items=cart.map(c=>{let x=menu.find(m=>m.id===c.id);return{name:x.name,price:x.price,qty:c.qty}}),total=items.reduce((s,x)=>s+x.price*x.qty,0);orders.unshift({id:Date.now(),name:$("customerName").value,phone:$("customerPhone").value,address:$("customerAddress").value,items,total,status:"New",date:new Date().toLocaleString()});cart=[];save();e.target.reset();closeModals();render();alert("Order placed successfully! Order #"+orders[0].id)}
function openAdmin(){$("adminModal").style.display="flex"}function adminLogin(e){e.preventDefault();if($("adminUser").value==="aroh097"&&$("adminPass").value==="Arun@123"){showAdmin()}else alert("Invalid login")}
function showAdmin(){let orderList=orders.map(o=>'<div class="admin-card"><b>Order #'+o.id+'</b><span class="badge">'+o.status+'</span><br><strong>'+o.name+'</strong> · '+o.phone+'<br>'+o.address+'<br>'+o.items.map(i=>i.name+" × "+i.qty).join(", ")+'<br><b>Total ₹'+o.total+'</b><br><small>'+o.date+'</small></div>').join("")||"<p>No orders yet.</p>";
let items=menu.map(x=>'<div class="admin-item"><img src="'+x.img+'"><div><b>'+x.name+'</b><div>₹'+x.price+'</div></div><button onclick="editMenu('+x.id+')">Edit</button><button class="danger" onclick="deleteMenu('+x.id+')">Delete</button></div>').join("");
$("adminContent").innerHTML='<div class="admin-head"><div><h2>Admin Dashboard</h2><p>Manage restaurant, food gallery and orders</p></div><button onclick="closeModals()">Logout</button></div><div class="admin-stats"><div><b>'+orders.length+'</b><small>Total Orders</small></div><div><b>'+menu.length+'</b><small>Menu Items</small></div><div><b>₹'+orders.reduce((s,o)=>s+o.total,0)+'</b><small>Order Value</small></div></div><section class="admin-section"><h3>Restaurant Settings</h3><div class="admin-form"><input id="newName" value="'+settings.name+'" placeholder="Restaurant name"><button class="primary" onclick="saveName()">Save Name</button></div></section><section class="admin-section"><h3>Food Photo Gallery</h3><div class="gallery">'+foodGallery.map((f,i)=>'<button class="gallery-card" onclick="selectGallery('+i+')"><img src="'+f[1]+'"><span>'+f[0]+'</span></button>').join("")+'</div><p id="selectedPhoto">Select a food photo to use.</p></section><section class="admin-section"><h3>Add / Edit Food</h3><div class="admin-form"><input id="mn" placeholder="Food name"><input id="mp" type="number" placeholder="Price"><input id="mi" type="hidden"><input id="editId" type="hidden"><label class="image-picker"><span id="imageLabel">📷 Select Image from Gallery</span><input id="imageFile" type="file" accept="image/*" onchange="selectLocalImage(event)"></label><button class="primary" onclick="saveMenuItem()">Save Food Item</button></div></section><section class="admin-section"><h3>Current Menu</h3>'+items+'</section><section class="admin-section"><h3>Order History</h3>'+orderList+'</section>'}
function selectGallery(i){$("mi").value=foodGallery[i][1];$("mn").value=foodGallery[i][0];$("imageLabel").textContent="🖼️ Gallery image selected";$("selectedPhoto").innerHTML='<img class="preview-photo" src="'+foodGallery[i][1]+'"> '+foodGallery[i][0]}
function saveName(){settings.name=$("newName").value||"My Restaurant";save();render();showAdmin()}
function selectLocalImage(e){const file=e.target.files[0];if(!file)return;if(file.size>2500000)return alert("Image should be under 2.5 MB");const reader=new FileReader();reader.onload=()=>{$("mi").value=reader.result;$("imageLabel").textContent="✅ "+file.name;$("selectedPhoto").innerHTML='<img class="preview-photo" src="'+reader.result+'"> Selected image'};reader.readAsDataURL(file)}
function saveMenuItem(){let n=$("mn").value,p=Number($("mp").value),img=$("mi").value,id=Number($("editId").value);if(!n||!p||!img)return alert("Name, price and photo required");if(id){let x=menu.find(m=>m.id===id);x.name=n;x.price=p;x.img=img}else menu.push({id:Date.now(),name:n,price:p,img});save();render();showAdmin()}
function editMenu(id){let x=menu.find(m=>m.id===id);showAdmin();$("mn").value=x.name;$("mp").value=x.price;$("mi").value=x.img;$("editId").value=x.id;$("imageLabel").textContent="🖼️ Current image";$("selectedPhoto").innerHTML='<img class="preview-photo" src="'+x.img+'"> Selected'}
function deleteMenu(id){if(confirm("Delete this food item?")){menu=menu.filter(x=>x.id!==id);save();render();showAdmin()}}
function closeModals(){document.querySelectorAll(".modal").forEach(x=>x.style.display="none")}render();