const express=require("express");
const cors=require("cors");
const fs=require("fs");
const path=require("path");
const app=express();
const PORT=process.env.PORT||10000;
const DATA=path.join(__dirname,"data.json");
const ADMIN_USER=process.env.ADMIN_USER||"aroh097";
const ADMIN_PASS=process.env.ADMIN_PASS||"Arun@123";
const GITHUB_TOKEN=process.env.GITHUB_TOKEN||"";
const GITHUB_REPO=process.env.GITHUB_REPO||"Arun282/Resturent";
const GITHUB_PATH=process.env.GITHUB_DATA_PATH||"data.json";
const GITHUB_BRANCH=process.env.GITHUB_BRANCH||"main";
const githubEnabled=Boolean(GITHUB_TOKEN);
app.use(cors());app.use(express.json({limit:"8mb"}));
const defaultMenu=[{id:1,name:"Butter Chicken",price:260,img:"https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80"},{id:2,name:"Paneer Tikka",price:220,img:"https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80"},{id:3,name:"Veg Biryani",price:180,img:"https://images.unsplash.com/photo-1563379091339-03246963d96c?auto=format&fit=crop&w=800&q=80"},{id:4,name:"Masala Dosa",price:140,img:"https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=800&q=80"}];
let db={menu:defaultMenu,orders:[],customers:[],coupons:[],ads:[],settings:{name:"My Restaurant",logo:""}},dataSha=null,saveQueue=Promise.resolve();
function normalize(){db=db&&typeof db==="object"?db:{};db.menu=Array.isArray(db.menu)?db.menu:defaultMenu;db.orders=Array.isArray(db.orders)?db.orders:[];db.customers=Array.isArray(db.customers)?db.customers:[];db.coupons=Array.isArray(db.coupons)?db.coupons:[];db.ads=Array.isArray(db.ads)?db.ads:[];db.admins=Array.isArray(db.admins)?db.admins:[];if(!db.admins.length)db.admins=[{id:1,user:ADMIN_USER,pass:ADMIN_PASS,recoveryPin:"1234"}];db.settings={name:db.settings?.name||"My Restaurant",logo:db.settings?.logo||""}}
async function githubGet(){const r=await fetch("https://api.github.com/repos/"+GITHUB_REPO+"/contents/"+GITHUB_PATH+"?ref="+encodeURIComponent(GITHUB_BRANCH),{headers:{Authorization:"Bearer "+GITHUB_TOKEN,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2026-03-10"}});if(r.status===404)return null;if(!r.ok)throw new Error("GitHub read failed: "+r.status);const x=await r.json();dataSha=x.sha;return JSON.parse(Buffer.from(x.content.replace(/\n/g,""),"base64").toString("utf8"))}
async function githubSave(){const body=JSON.stringify(db,null,2);let payload={message:"Update restaurant data",content:Buffer.from(body).toString("base64"),branch:GITHUB_BRANCH};if(dataSha)payload.sha=dataSha;let r=await fetch("https://api.github.com/repos/"+GITHUB_REPO+"/contents/"+GITHUB_PATH,{method:"PUT",headers:{Authorization:"Bearer "+GITHUB_TOKEN,Accept:"application/vnd.github+json","Content-Type":"application/json","X-GitHub-Api-Version":"2026-03-10"},body:JSON.stringify(payload)});if(r.status===409){await githubGet();payload.sha=dataSha;r=await fetch("https://api.github.com/repos/"+GITHUB_REPO+"/contents/"+GITHUB_PATH,{method:"PUT",headers:{Authorization:"Bearer "+GITHUB_TOKEN,Accept:"application/vnd.github+json","Content-Type":"application/json","X-GitHub-Api-Version":"2026-03-10"},body:JSON.stringify(payload)})}if(!r.ok)throw new Error("GitHub save failed: "+r.status+" "+await r.text());const x=await r.json();dataSha=x.content?.sha||dataSha}
function save(){saveQueue=saveQueue.then(async()=>{if(githubEnabled)await githubSave();else fs.writeFileSync(DATA,JSON.stringify(db,null,2))}).catch(e=>console.error(e));return saveQueue}
async function load(){if(githubEnabled){const remote=await githubGet();if(remote)db=remote;else await githubSave()}else if(fs.existsSync(DATA)){try{db=JSON.parse(fs.readFileSync(DATA,"utf8"))}catch(e){console.error(e)}}normalize()}
function admin(req){const u=req.headers["x-admin-user"],p=req.headers["x-admin-pass"];return db.admins.some(a=>a.user===u&&a.pass===p)}
function customer(req){return db.customers.find(c=>c.token===req.headers["x-customer-token"])}
app.post("/api/customer/signup",async(req,res)=>{const {name,phone,password,address,recoveryPin}=req.body;if(!name||!phone||!password||!recoveryPin)return res.status(400).json({error:"Name, mobile, password and recovery PIN required"});const p=String(phone).replace(/\D/g,"");if(p.length!==10)return res.status(400).json({error:"Mobile number must be exactly 10 digits"});if(db.customers.some(c=>c.phone===p))return res.status(409).json({error:"Mobile number already registered"});const c={id:Date.now(),name:String(name).trim(),phone:p,password:String(password),address:String(address||"").trim(),recoveryPin:String(recoveryPin).trim(),token:require("crypto").randomBytes(24).toString("hex")};db.customers.push(c);await save();res.json({id:c.id,name:c.name,phone:c.phone,address:c.address||"",token:c.token})});
app.post("/api/customer/forgot-password",async(req,res)=>{const p=String(req.body.phone||"").replace(/\D/g,""),pin=String(req.body.pin||""),np=String(req.body.newPassword||"");if(p.length!==10||!pin||np.length<4)return res.status(400).json({error:"Mobile, recovery PIN and new password required"});const c=db.customers.find(x=>x.phone===p);if(!c)return res.status(404).json({error:"Customer account not found"});if(!c.recoveryPin)return res.status(400).json({error:"Recovery PIN is not set"});if(c.recoveryPin!==pin)return res.status(401).json({error:"Invalid recovery PIN"});c.password=np;await save();res.json({ok:true})});
app.post("/api/customer/login",async(req,res)=>{const p=String(req.body.phone||"").replace(/\D/g,"");if(p.length!==10)return res.status(400).json({error:"Mobile number must be exactly 10 digits"});const c=db.customers.find(x=>x.phone===p&&x.password===String(req.body.password||""));if(!c)return res.status(401).json({error:"Invalid mobile or password"});res.json({id:c.id,name:c.name,phone:c.phone,address:c.address||"",token:c.token})});
app.put("/api/customer/profile",async(req,res)=>{const c=customer(req);if(!c)return res.status(401).json({error:"Customer login required"});if(typeof req.body.name==="string"&&req.body.name.trim())c.name=req.body.name.trim();if(typeof req.body.address==="string")c.address=req.body.address.trim();await save();res.json({id:c.id,name:c.name,phone:c.phone,address:c.address||"",token:c.token})});
app.get("/api/customer/orders",async(req,res)=>{const c=customer(req);if(!c)return res.status(401).json({error:"Customer login required"});res.json(db.orders.filter(o=>String(o.phone).replace(/\D/g,"")===c.phone))});
app.get("/api/menu",(req,res)=>res.json(db.menu));app.get("/api/settings",(req,res)=>res.json(db.settings));app.get("/api/ads",(req,res)=>res.json(db.ads.filter(a=>a.active!==false)));
app.get("/api/admin/ads",(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});res.json(db.ads)});
app.post("/api/admin/ads",async(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});const {title,type,media,link}=req.body;if(!title||!media||!["image","video"].includes(type))return res.status(400).json({error:"Title, media and type required"});const ad={id:Date.now(),title:String(title).trim(),type,media:String(media),link:String(link||""),active:true};db.ads.unshift(ad);await save();res.json(ad)});
app.patch("/api/admin/ads/:id",async(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});const ad=db.ads.find(x=>String(x.id)===String(req.params.id));if(!ad)return res.status(404).json({error:"Ad not found"});if(typeof req.body.active==="boolean")ad.active=req.body.active;if(typeof req.body.title==="string"&&req.body.title.trim())ad.title=req.body.title.trim();if(typeof req.body.media==="string"&&req.body.media)ad.media=req.body.media;if(["image","video"].includes(req.body.type))ad.type=req.body.type;if(typeof req.body.link==="string")ad.link=req.body.link;await save();res.json(ad)});
app.delete("/api/admin/ads/:id",async(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});db.ads=db.ads.filter(x=>String(x.id)!==String(req.params.id));await save();res.json({ok:true})});
app.get("/api/orders/:id",(req,res)=>{const o=db.orders.find(x=>String(x.id)===String(req.params.id));if(!o)return res.status(404).json({error:"Order not found"});res.json(o)});
app.post("/api/coupons/apply",async(req,res)=>{if(!customer(req))return res.status(401).json({error:"Customer login required"});const code=String(req.body.code||"").trim().toUpperCase(),subtotal=Number(req.body.subtotal)||0,cp=db.coupons.find(x=>x.code===code&&x.active!==false);if(!code)return res.status(400).json({error:"Coupon code required"});if(!cp)return res.status(404).json({error:"Invalid or inactive coupon"});if(cp.minOrder&&subtotal<Number(cp.minOrder))return res.status(400).json({error:"Minimum order ₹"+cp.minOrder+" required"});let discount=cp.type==="percent"?subtotal*Number(cp.value)/100:Number(cp.value);discount=Math.max(0,Math.min(discount,subtotal));res.json({code:cp.code,discount:Math.round(discount),total:Math.max(0,subtotal-Math.round(discount))})});
app.post("/api/orders",async(req,res)=>{const c=customer(req),{name,phone,address,items,total,coupon,discount}=req.body;if(!c)return res.status(401).json({error:"Customer login required"});if(!name||!phone||!address||!Array.isArray(items)||!items.length)return res.status(400).json({error:"Missing order details"});const o={id:Date.now(),name,phone,address,items,total:Number(total)||0,subtotal:Math.max(0,Number(total)||0),coupon:coupon||"",discount:Number(discount)||0,status:"New",date:new Date().toLocaleString("en-IN")};db.orders.unshift(o);await save();res.json(o)});
app.get("/api/orders",(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});res.json(db.orders)});
app.delete("/api/orders/:id",async(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});const before=db.orders.length;db.orders=db.orders.filter(x=>String(x.id)!==String(req.params.id));if(db.orders.length===before)return res.status(404).json({error:"Order not found"});await save();res.json({ok:true})});
app.patch("/api/orders/:id/status",async(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});const o=db.orders.find(x=>String(x.id)===String(req.params.id));if(!o)return res.status(404).json({error:"Order not found"});const s=req.body.status;if(!["Accepted","Rejected","Delivered"].includes(s))return res.status(400).json({error:"Invalid status"});if(s==="Delivered"&&o.status!=="Accepted")return res.status(400).json({error:"Order must be accepted first"});o.status=s;await save();res.json(o)});
app.post("/api/admin/forgot-password",async(req,res)=>{const u=String(req.body.user||"").trim(),pin=String(req.body.pin||""),np=String(req.body.newPassword||"");if(!u||!pin||np.length<4)return res.status(400).json({error:"Username, recovery PIN and new password required"});const a=db.admins.find(x=>x.user===u);if(!a)return res.status(404).json({error:"Admin not found"});if(a.recoveryPin!==pin)return res.status(401).json({error:"Invalid recovery PIN"});a.pass=np;await save();res.json({ok:true})});
app.post("/api/admin/login",(req,res)=>{const u=String(req.body.user||"").trim(),p=String(req.body.pass||"");if(db.admins.some(a=>a.user===u&&a.pass===p))return res.json({ok:true});res.status(401).json({error:"Invalid admin username or password"})});
app.get("/api/admin/admins",(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});res.json(db.admins.map(a=>({id:a.id,user:a.user})))});
app.post("/api/admin/admins",async(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});const u=String(req.body.user||"").trim(),p=String(req.body.pass||""),pin=String(req.body.recoveryPin||"").trim();if(!u||p.length<4||!pin)return res.status(400).json({error:"Username, password and recovery PIN required"});if(db.admins.some(a=>a.user===u))return res.status(409).json({error:"Admin username already exists"});const a={id:Date.now(),user:u,pass:p,recoveryPin:pin};db.admins.push(a);await save();res.json({id:a.id,user:a.user})});
app.get("/api/coupons",(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});res.json(db.coupons)});
app.post("/api/coupons",async(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});const code=String(req.body.code||"").trim().toUpperCase(),type=req.body.type==="percent"?"percent":"fixed",value=Number(req.body.value),minOrder=Math.max(0,Number(req.body.minOrder)||0);if(!code||!/^[A-Z0-9_-]{3,20}$/.test(code)||!value||value<0)return res.status(400).json({error:"Valid coupon code and value required"});if(type==="percent"&&value>100)return res.status(400).json({error:"Percentage cannot exceed 100"});if(db.coupons.some(x=>x.code===code))return res.status(409).json({error:"Coupon already exists"});const cp={id:Date.now(),code,type,value,minOrder,active:true};db.coupons.push(cp);await save();res.json(cp)});
app.patch("/api/coupons/:id",async(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});const cp=db.coupons.find(x=>String(x.id)===String(req.params.id));if(!cp)return res.status(404).json({error:"Coupon not found"});cp.active=req.body.active!==false;await save();res.json(cp)});
app.delete("/api/coupons/:id",async(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});db.coupons=db.coupons.filter(x=>String(x.id)!==String(req.params.id));await save();res.json({ok:true})});
app.put("/api/settings",async(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});db.settings={...db.settings,name:req.body.name||"My Restaurant",logo:typeof req.body.logo==="string"?req.body.logo:db.settings.logo||""};await save();res.json(db.settings)});
app.post("/api/menu",async(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});const x={id:Date.now(),name:req.body.name,price:Number(req.body.price),img:req.body.img};if(!x.name||!x.price||!x.img)return res.status(400).json({error:"Name, price and photo required"});db.menu.push(x);await save();res.json(x)});
app.put("/api/menu/:id",async(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});const x=db.menu.find(m=>String(m.id)===String(req.params.id));if(!x)return res.status(404).json({error:"Food not found"});x.name=req.body.name;x.price=Number(req.body.price);x.img=req.body.img;await save();res.json(x)});
app.delete("/api/menu/:id",async(req,res)=>{if(!admin(req))return res.status(401).json({error:"Unauthorized"});db.menu=db.menu.filter(m=>String(m.id)!==String(req.params.id));await save();res.json({ok:true})});
app.use(express.static(__dirname));app.use((req,res)=>res.sendFile(path.join(__dirname,"index.html")));
load().then(()=>app.listen(PORT,()=>console.log("Restaurant server running on "+PORT+" | storage="+(githubEnabled?"github":"local")))).catch(e=>{console.error(e);process.exit(1)});
